name: phys320
channels:
  - conda-forge
dependencies:
  - llvm-openmp<=20.1.8
  - matplotlib
  - scipy
  - ipympl
  - numpy
  - pyvisa
  - jupyterlab
  - python=3.12
  - ipywidgets
  - zeroconf
  - notebook
  - pandas
